geekshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('shop/', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path('date_and_title/', mainapp.date_and_title, name='date_and_title'),
    path('auth/', include('authapp.urls', namespace='auth')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from mainapp.views import products, contact

urlpatterns = [
    path('products/', products, name='products'),
    path('contact/', contact, name='contact'),
]

geekshop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='Возраст')

geekshop/mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'categories'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='Краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='Описание продукта', blank=True)
    price = models.DecimalField(verbose_name='Цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='Количество на складе', default=0)

    def __str__(self):
        return f'{self.name} {self.category.name}'

    class Meta:
        db_table = 'products'

geekshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django import forms

from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Вы слишком молоды')

        return data

geekshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm
from django.contrib import auth
from django.urls import reverse
from authapp.forms import ShopUserRegisterForm
from authapp.forms import ShopUserEditForm


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)


def edit(request):
    title = 'Редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    content = {'title': title, 'edit_form': edit_form}

    return render(request, 'authapp/edit.html', content)

geekshop/mainapp/views.py
from django.shortcuts import render

# Create your views here.
from .models import Product

content = {
    'links': [
        {'href': 'main', 'name': 'домой'},
        {'href': 'products', 'name': 'продукты'},
        {'href': 'contact', 'name': 'контакты'},
    ]
}


def main(request):
    content['title_and_prod'] = {'title': 'Главная', 'products': Product.objects.all()}
    return render(request, 'mainapp/index.html', content)


def products(request):
    return render(request, 'mainapp/products.html', content)


def contact(request):
    return render(request, 'mainapp/contact.html', content)


def date_and_title(request):
    return render(request, 'mainapp/date_and_title.html')

geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
         {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="login">
        <div class="h2 text-center head">
            {% block h2 %}
            {% endblock %}
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

geekshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'main' %}" class="">
            на главную
        </a>
    </button>
    <div class="user_avatar"><img src="/media/{{ user.avatar }}"></div>
{% endblock %}

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block h2 %}
    Вход в систему
{% endblock %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>

{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block h2 %}
    {{ title|title }}
{% endblock %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Зарегистрироваться">
    </form>
{% endblock %}

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="container">

    <div class="{% block header_class%}slider{% endblock %}">

    {% block header%}
    {% include 'mainapp/includes/inc_header.html' %}
    {% endblock %}
    {% block bottom_of_header %}
    {% endblock %}
    </div>
    {% block content %}
    {% endblock %}
    <div class="clr"></div>
</div>

{% block footer %}
{% include 'mainapp/includes/inc_footer.html' %}
{% endblock %}

{% for product in title_and_prod.products %}
  <div class="block">
    <a href="#">
      <img src="{{ product.image }}" alt="{{ product.short_desc }}">
      <div class="text">
        <h3>{{ product.category.name }}</h3>
        <h4>{{ product.name }}</h4>
        <p>{{ product.description }}</p>
      </div>
    </a>
  </div>
{% endfor %}

</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}Контакты{% endblock %}

{% block header_class%}hero{% endblock %}

{% block bottom_of_header %}
<h1>наши контакты</h1>
{% endblock %}

{% block content %}
<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/date_and_title.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>Date experiments</h3>
    {% now 'Y' %}
    <br>
    <br>
    {% now 'jS F Y H:i' %}
    <br>
    <p>Now {% now 'zS' %} day and {% now 'WS' %} week of {% now 'Y' %} year.
       Number of days in {% now 'F' %} is {% now 't' %}.
       It's {% now 'f a' %} now.
    </p>
    <p>It is the {% now "jS \o\f F" %}</p>
    <p>It is {% now "SHORT_DATETIME_FORMAT" %}</p>
    <h3>Title experiments</h3>
    <p> {% with 'that should be enough' as text %}
        {% for i in text.split %}
        {{ i|title }}
        {% endfor %}
        {% endwith %}
    </p>

</body>
</html>

geekshop/mainapp/templates/mainapp/includes/inc_footer.html
{% block footer %}
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2017</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/includes/inc_header.html
{% block header%}
    <div class="header clearfix">
        <a href="index.html" class="logo"></a>
        {% block menu %}
        {% include 'mainapp/includes/inc_menu.html' %}
        {% endblock %}
        <a href="#" class="search"></a>
        <a href="#" class="basket"></a>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/includes/inc_menu.html
{% block menu %}
<ul class="menu">

    {% for link in links %}
    <li>
        <a href="{% url link.href %}" class="
            {% if request.resolver_match.url_name == link.href %}
                active
            {% endif %}">
            {{ link.name }}
        </a>
    </li>
    {% endfor %}

    {% if user.is_authenticated %}
    <li>
        <a href="{% url 'auth:edit' %}">
            {{ user.first_name|default:'Пользователь' }}
        </a>
    </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>


</ul>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}Магазин{% endblock %}

{% block header_class%}slider{% endblock %}

{% block bottom_of_header %}
<div class="text-slider">
    <h3 class="green">тенденции</h3>
    <h3 class="big"> удобные стулья</h3>
    <p>Новый уровень комфорта. Отличные характеристики.</p>
    <a href="#" class="button-order">заказать <img src="/static/img/arrow.png" alt=""></a>
</div>
<div class="navi">
    <a href="#"></a><a href="#"></a><a href="#"></a>
</div>
{% endblock %}

{% block content %}
<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
    <div class="clearfix">
    </div>
    <div class="tab-content">
        <div class="block">
            <a href="#"><img src="/static/img/product-1.jpg" alt="">
                <div class="text">
                    <img src="/static/img/icon-hover.png" alt="img">
                    <h4>Отличный стул</h4>
                    <p>Расположитесь комфортно. </p>
                </div>
            </a>
        </div>
        <div class="block">
            <a href="#"><img src="/static/img/product-2.jpg" alt="">
                <div class="text">
                    <img src="/static/img/icon-hover.png" alt="">
                    <h4>Стул повышенного качества</h4>
                    <p>Не оторваться. </p>
                </div>
            </a>
        </div>
    </div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}Каталог{% endblock %}

{% block header_class%}hero-white{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        <ul class="links-menu">
            <li><a href="#" class="active">все</a></li>
            <li><a href="#">дом</a></li>
            <li><a href="#">офис</a></li>
            <li><a href="#">модерн</a></li>
            <li><a href="#">классика</a></li>
        </ul>
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/static/img/slider1.jpg">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/static/img/controll.jpg" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/static/img/controll1.jpg" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/static/img/controll2.jpg" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">Отличный стул</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price"> 2585.9 <span>руб</span></p>
            <a href="#" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                <p>Расположитесь комфортно.</p>
                <p>Отличное качество материалов
                    позволит вам это.</p>
                <p>Различные цвета</p>
                <p>высочайший уровень
                    эргономики и прочность.</p>
            </div>
        </div>
    </div>

    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
        </div>
        <div class="related-products clearfix">
            <div class="block">
                <a href="#"><img src="/static/img/product-11.jpg" alt="">
                    <div class="text">
                        <img src="/static/img/icon-hover.png" alt="img">
                        <h4>Стул повышенного качества</h4>
                        <p>Не оторваться. </p>
                    </div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="/static/img/product-21.jpg" alt="">
                    <div class="text">
                        <img src="/static/img/icon-hover.png" alt="img">
                        <h4>Стул повышенного качества</h4>
                        <p>Не оторваться. </p>
                    </div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="/static/img/product-31.jpg" alt="">
                    <div class="text">
                        <img src="/static/img/icon-hover.png" alt="img">
                        <h4>Стул повышенного качества</h4>
                        <p>Не оторваться. </p>
                    </div>
                </a>
            </div>

        </div>
    </div>
</div>
{% endblock %}